version: "3.9"

services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    networks:
      - backend
    depends_on:
      - db
    tty: true      
    environment:
        GO_ENV: docker
    command:  sh -c '/app/scripts/wait-for db:5432 -- /app/timetrack'

  db:
    image: postgres:14-alpine
    environment:
      - POSTGRES_DB=timetracker
      - POSTGRES_USER=timetraveler
      - POSTGRES_PASSWORD=timetraveler_changeme
    ports:
      - '5432:5432'
    volumes:
      - ./database/schema-1.sql:/docker-entrypoint-initdb.d/1-schema.sql
      - ./database/example-data.sql:/docker-entrypoint-initdb.d/2-data.sql
      - data:/var/lib/postgresql/data
    networks:
      - backend

volumes:
  data:

networks:
  backend:
    driver: bridge