application:
  hostname: localhost
  port: 8000
  delayRequestMilliSeconds: 0
  profileEnabled: false

logging:
  output: production
  enableStacktrace: false

postgres:
  username: timemaster
  database: timetracker
  sslmode: require
  timeout: 60 #seconds
  connectLifetime: 2
  maxIdle: 10
  maxOpen: 20
  master:
    host: localhost
    port: 5432

cors:
  enabled: false
  maxAge: 1209600