application:
  hostname: localhost
  port: 8000
  applicationDomain: localhost
  applicationDomainPort: 3000
  domainSecure: false
  delayRequestMilliSeconds: 0
  profileEnabled: false

logging:
  output: production
  enableStacktrace: false

postgres:
  username: timemaster
  database: timetracker
  sslmode: require
  timeout: 60 #seconds
  connectLifetime: 2
  maxIdle: 10
  maxOpen: 20
  master:
    host: localhost
    port: 5432

cors:
  enabled: false
  maxAge: 1209600

email:
  enabled: true
  testMode: true # only send to `testToEmail` address
  fromName: Time Tracker
  emailSignatureName: The Time Tracker Team
  fromAddress: time@example.com
  testToEmail: test@example.com
  sendGrid:
    apiKey: SENDGRID-PUT-YOUR-API-KEY-HERE

session:
  cookieName: tt.session
  tokenLength: 64
  secret: !!!THIS_IS_VERY_SECRET_PLEASE_CHANGE_IT!!!
  tokenExpirationMinutes: 43200 # 60 * 24 * 30 = 30 days
  cookieExpirationMinutes: 43200 # 60 * 24 * 30 = 30 days
  secureCookie: false
  maxFailedLoginAttempts: 6
  loginFailureWindowMinutes: 5
  profileLockDurationMinutes: 15
  forgotPasswordTokenLength: 256
  forgotPasswordExpirationInMinutes: 2880 # 60 * 24 * 2 = 2 days
  addUserTokenExpirationInMinutes: 7200 # 60 * 24 * 2 = 5 days
  clearForgotPasswordOnValidate: true  # clear the forgot_password_token and expiration when validated
