name: build
on:
  push:
    branches: 
      - master

jobs:

  build-test:
    runs-on: ubuntu-latest

    services:
      postgres:  # Label used to access the service container
        image: postgres
        options: --name=postgres
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: timetracker
          POSTGRES_PORT: 5432
          options: --health-cmd pg_isready --health-interval 10s --health-timeout 5s --health-retries 5

    steps:
    - name: Set up Go 1.14
      uses: actions/setup-go@v1
      with:
        go-version: 1.14.2
      id: go

    - name: Check out code into the Go module directory
      uses: actions/checkout@v2

    - name: Build
      run: make build
  
    - name: Unit Tests
      run: make unit_test
      env:
        GO_ENV: test

    - name: Install Libraries
      run: |
        sudo apt-get update
        sudo apt-get install -y postgresql-client
    - name: Bootstrap PostgreSQL
      run: |
        echo "Postgres"
        psql -h localhost -U postgres -a -f ./database/bootstrap.sql

    - name: Create PostgreSQL schema
      run: |
        echo "Postgres"
        psql -h localhost -U postgres -d timetracker -a -f ./database/schema-1.sql

    - name: Integration Tests
      run: make int_test
      env:
        GO_ENV: test
